language: node_js
node_js:
  - "lts/*"
deploy:
  - provider: script
    skip_cleanup: true
    script: yarn prepare
    on:
      tags: true
  - provider: script
    skip_cleanup: true
    script: yarn prepare
    on:
      branch: main
