version: 2.1
orbs:
  node: circleci/node@4.7
  codecov: codecov/codecov@3.2.4
workflows:
  build:
    jobs:
      - node/test:
          version: 'lts'
          pkg-manager: yarn
          post-steps:
            - codecov/upload